kind: Pod
apiVersion: v1
metadata:
  name: annotations
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20hours'